name: Build Flutter APK

# 触发构建的事件，可以设置为 push 到某个分支，或是 pull request
on:
  push:
    branches:
      - master # 或者你想要触发构建的分支
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的 Ubuntu 环境构建

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 设置 Flutter 环境，指定旧版本（例如：1.22.6）
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '1.22.6'  # 使用旧版 Flutter，防止使用 Android v2 embedding

      # 安装依赖
      - name: Install dependencies
        run: |
          flutter pub get
          
      # 运行 Flutter 构建命令
      - name: Build APK
        run: |
          flutter build apk --release  # 你可以选择 build apk --debug 或者 --profile

      # 上传生成的 APK 作为构建工件
      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
