name: Build Flutter APK

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '1.22.6'

      - name: Install Android SDK and NDK
        run: |
          # 安装 Android SDK 和 NDK
          sudo apt-get install -y wget unzip openjdk-8-jdk
          # 设置 Android SDK 路径
          echo "y" | sdkmanager --licenses
          sdkmanager "platforms;android-28" "platforms;android-29" "build-tools;29.0.3" "ndk;21.4.7075529"
          
      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
